syntax = "proto3";

package message;

option py_generic_services = true;

enum MessageType {
  MESSAGE_UNSPECIFIED = 0;
  MESSAGE_CLIENT_CONFIGURE_SESSION = 1;
  MESSAGE_SERVER_CONFIRM_SESSION = 2;
  MESSAGE_CLIENT_AUDIO_INPUT = 3;
  MESSAGE_SERVER_ERROR = 4;
  MESSAGE_SERVER_RESPONSE_ANIMATION = 5;
  MESSAGE_CLIENT_INTERRUPT = 7;
}

enum AudioFormat {
  AUDIO_FORMAT_PCM_S16LE = 0;
  AUDIO_FORMAT_OGG_OPUS = 1;
}

enum TransportCompression {
  TRANSPORT_COMPRESSION_NONE = 0;
}

enum EgressType {
  EGRESS_TYPE_UNSPECIFIED = 0;
  EGRESS_TYPE_LIVEKIT = 1;
  EGRESS_TYPE_AGORA = 2;
}

message LiveKitEgressConfig {
  string url = 1;
  string api_key = 2;
  string api_secret = 3;
  string room_name = 4;
  string publisher_id = 5;
  map<string, string> extra_attributes = 6;
  int32 idle_timeout = 7;
  string api_token = 8;
}

message AgoraEgressConfig {
  string channel_name = 1;
  string token = 2;
  uint32 uid = 3;
  string publisher_id = 4;
}

message ClientConfigureSession {
  int32 sample_rate = 1;
  int32 bitrate = 2;
  AudioFormat audio_format = 3;
  TransportCompression transport_compression = 4;
  EgressType egress_type = 5;
  LiveKitEgressConfig livekit_egress = 6;
  AgoraEgressConfig agora_egress = 7;
  map<string, string> extra_params = 8;
}

message ServerConfirmSession {
  string connection_id = 1;
}

message TraceContext {
  string traceparent = 1;
  string tracestate = 2;
}

message ClientAudioInput {
  string req_id = 1;
  bool end = 2;
  bytes audio = 3;
  TraceContext trace_context = 4;
}

message ServerError {
  string connection_id = 1;
  string req_id = 2;
  int32 code = 3;
  string message = 4;
}

message ServerResponseAnimation {
  string connection_id = 1;
  string req_id = 2;
  bool end = 3;
}

message ClientInterrupt {
  string req_id = 1;
}

message Message {
  MessageType type = 1;
  oneof data {
    ClientConfigureSession client_configure_session = 2;
    ServerConfirmSession server_confirm_session = 3;
    ClientAudioInput client_audio_input = 4;
    ServerError server_error = 5;
    ServerResponseAnimation server_response_animation = 6;
    ClientInterrupt client_interrupt = 8;
  }
}
